theme: jekyll-theme-minimal
logo: https://avatars2.githubusercontent.com/u/27868542?s=460&u=42a83bbbb076f088fa73665b9b427439e42db64a&v=4
favicon: https://avatars2.githubusercontent.com/u/27868542?s=460&u=42a83bbbb076f088fa73665b9b427439e42db64a&v=4
title: Lunekiska's Homepage UwU
description: Welcome wanderer to my page OwO
